on:
  push:
    branches:
      - main

name: Go Build (ko.build)

jobs:
  build:
    name: Go Build and Release
    runs-on: skywalker-arc-runner-set
    environment: release
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Setup ko
        run: go install github.com/google/ko@v0.17.1

      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          allow-no-subscriptions: true
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}

      - name: Get ACR token
        id: acr-credential
        run: |
          echo "acr-credential<<EOF" >> $GITHUB_OUTPUT
          az acr login --subscription ${{ vars.container_registry_azure_subscription_id }} --expose-token --name ${{ vars.azure_container_registry }} --output json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Log in to ACR
        run: |
          ko login --username 00000000-0000-0000-0000-000000000000 --password "${{ fromJSON(steps.acr-credential.outputs.acr-credential).accessToken }}" "${{ fromJSON(steps.acr-credential.outputs.acr-credential).loginServer }}"

      - run: |
          ko build \
            --base-import-paths \
            --tags ${{ github.ref_name }} \
            --image-annotation "org.opencontainers.image.authors=Organa,org.opencontainers.image.created=$(date --iso-8601=seconds),org.opencontainers.image.source=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY},org.opencontainers.image.vendor=Organa,org.opencontainers.image.url=${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/releases" \
            .
        env:
          KO_DOCKER_REPO: ${{ vars.azure_container_registry }}.azurecr.io
          GOPRIVATE: github.com/politiet
          VERSION: ${{ github.ref_name }}